AWSTemplateFormatVersion: 2010-09-09
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: CloudFormation Setting
      Parameters:
      - Prefix
    - Label:
        default: VPC Setting
      Parameters:
      - CidrVpc
    - Label:
        default: Public Subnets Setting
      Parameters:
      - CidrSubnet1aPublic
      - CidrSubnet1cPublic
      - CidrSubnet1dPublic
    - Label:
        default: Private Subnets Setting
      Parameters:
      - CidrSubnet1aPrivate
      - CidrSubnet1cPrivate
      - CidrSubnet1dPrivate
Parameters:
  Prefix:
    Type: String
    Default: myecs
  CidrVpc:
    Type: String
    Default: 10.0.0.0/16
  CidrSubnet1aPublic:
    Type: String
    Default: 10.0.0.0/24
  CidrSubnet1cPublic:
    Type: String
    Default: 10.0.1.0/24
  CidrSubnet1dPublic:
    Type: String
    Default: 10.0.2.0/24
  CidrSubnet1aPrivate:
    Type: String
    Default: 10.0.10.0/24
  CidrSubnet1cPrivate:
    Type: String
    Default: 10.0.11.0/24
  CidrSubnet1dPrivate:
    Type: String
    Default: 10.0.12.0/24
Resources:
  # ------------------------------------------------------------#
  # VPC
  # ------------------------------------------------------------#
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrVpc
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Sub ${Prefix}-vpc
  # ------------------------------------------------------------#
  # Public Subnets
  # ------------------------------------------------------------# 
  Subnet1aPublic:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}a
      CidrBlock: !Ref CidrSubnet1aPublic
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${Prefix}-subnet-1a-public
  Subnet1cPublic:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}c
      CidrBlock: !Ref CidrSubnet1cPublic
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${Prefix}-subnet-1c-public
  Subnet1dPublic:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}d
      CidrBlock: !Ref CidrSubnet1dPublic
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${Prefix}-subnet-1d-public
  # ------------------------------------------------------------#
  # Private Subnets
  # ------------------------------------------------------------# 
  Subnet1aPrivate:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}a
      CidrBlock: !Ref CidrSubnet1aPrivate
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${Prefix}-subnet-1a-private
  Subnet1cPrivate:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}c
      CidrBlock: !Ref CidrSubnet1cPrivate
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${Prefix}-subnet-1c-private
  Subnet1dPrivate:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}d
      CidrBlock: !Ref CidrSubnet1dPrivate
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${Prefix}-subnet-1d-private
  # ------------------------------------------------------------#
  # Network Routing
  # ------------------------------------------------------------#
  IgwVpc:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${Prefix}-igw
  IgwVpcAtch:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IgwVpc
      VpcId: !Ref Vpc
  RtSubnet:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: !Sub ${Prefix}-rt-subnet
  RoutePublic:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RtSubnet
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IgwVpc
  RtAssocPublic1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet1aPublic
      RouteTableId: !Ref RtSubnet
  RtAssocPublic1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet1cPublic
      RouteTableId: !Ref RtSubnet
  RtAssocPublic1d:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet1dPublic
      RouteTableId: !Ref RtSubnet