# Ref：https://dev.classmethod.jp/articles/cfn-create-waf-log-2021

AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Prefix:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: "Fill in the name of the system name."
  Env:
    Type: String
    Default: develop
    Description: "Fill in the name of the environment."
  Scope:
    Type: String
    Default: REGIONAL
    Description: "Fill in the scope of waf(REGIONAL or CLOUDFRONT)"
  WebAclAssociationResourceArn:
    Type: String
    Default: "arn:aws:elasticloadbalancing:<Region>:XXXXXXXXXXXX:loadbalancer/app/XXXXXXXXXXXX"
    Description: Enter RegionalResource(ALB,APIGateway,AppSync) ARN or CloudFront ARN to associate with WEBACL.
Resources:
# ------------------------------------------------------------#
# S3 (ログの保存に使うだけの)
# ------------------------------------------------------------#
  S3BacketForWaflog:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub aws-waf-logs-${Env}-${Prefix}-${AWS::AccountId}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
  S3BacketForAthenaQuery:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub athena-query-results-${Env}-${Prefix}-${AWS::AccountId}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
# ------------------------------------------------------------#
# WAF v2
# ------------------------------------------------------------#
  WebAcl:
    Type: AWS::WAFv2::WebACL # wafの作成
    Properties: 
      Name: !Sub ${Env}-${Prefix}-web-acl
      Scope: !Ref Scope # -> REGIONAL: ALBに紐付けるため
      DefaultAction: # 3つ (OverrideAction >= RuleAction > DefaultAction)
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true # クラウドウォッチの有効/無効
        SampledRequestsEnabled: true
        MetricName: !Sub ${Env}-${Prefix}-web-acl
      Rules:
        -
          Name: AWS-AWSManagedRulesCommonRuleSet # AWSで元々用意されたルール
          Priority: 1 # (必須) 0に近いほど優先度が高まる
          Statement:
            ManagedRuleGroupStatement: # ルールグループ
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction: # アクションの設定: ルールグループを使用している際に必要となる
            Count: {} # count: ログの出力 | none: ブロック
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSet
  WAFLogConfig: 
    Type: AWS::WAFv2::LoggingConfiguration # ログをどこに保存するか
    Properties:
      LogDestinationConfigs:
        - !GetAtt S3BacketForWaflog.Arn # ※s3の保存となるケースが多い
      ResourceArn: !GetAtt WebAcl.Arn # aclの指定
  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation # どのリソースに対してwafをつけるか
    Properties:
      ResourceArn: !Ref WebAclAssociationResourceArn # ここでfargateを指定する予定
      WebACLArn: !GetAtt WebAcl.Arn # aclの指定